// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import "./CreatorRegistry.sol";
import "./DeviceRegistry.sol";
import "./Licensing.sol";

/**
 * @dev A unified asset structure.
 * For an Original asset, captureTime and device are set.
 * For an Edited asset, sourceAssetId (pointer to the source asset) and transformation
 * describe the edit. Proofs are not stored.
 */
struct Asset {
    address creator;               // Creator's address.
    uint256 imageHash;             // Hash of the asset data.
    uint256 captureTime;           // Unix timestamp when the image was captured (for originals).
    License license;               // Licensing details.
    uint256 timestamp;             // Registration timestamp.
    uint256 sourceAssetId;         // For edited assets: pointer to the source asset; 0 if not applicable.
    Transformation transformation; // For edited assets: description of the applied transformation.
}

/**
 * @dev Enum for asset transformations.
 * These are the transformations that can be applied to an asset.
 */
enum Transformation {
    Blur,
    Brightness,
    Contrast,
    Crop,
    Grayscale,
    Redact,
    Resize,
    Sharpness,
    NoTransformation // Used for original assets.
}

/**
 * @dev Interface for the SNARK verifier.
 * This interface is used to verify proofs generated by the SNARK.
 */
interface ISnarkVerifier {
    function verifyOpaqueNovaProofWithInputs(
        uint256 steps,
        uint256[2] calldata initial_state,
        uint256[2] calldata final_state,
        uint256[25] calldata proof
    ) external view returns (bool);
}

/**
 * @title AssetGateway
 * @dev Main entry point for registering assets in the marketplace.
 */
contract AssetGateway {
    CreatorRegistry public creatorRegistry;
    DeviceRegistry public deviceRegistry;
    mapping(Transformation => ISnarkVerifier) public transformationVerifiers;

    uint256 public assetCount;

    // Mapping from asset ID to Asset details.
    mapping(uint256 => Asset) public assets;

    event AssetRegistered(
        uint256 indexed assetId,
        address indexed creator,
        uint256 imageHash,
        uint256 captureTime,
        License license,
        address device,
        uint256 sourceAssetId,
        Transformation transformation,
        uint256 timestamp
    );

    /**
     * @notice Constructor initializes the contract with the CreatorRegistry and DeviceRegistry.
     * @param _creatorRegistry Address of the deployed CreatorRegistry contract.
     * @param _deviceRegistry Address of the deployed DeviceRegistry contract.
     */
    constructor(address _creatorRegistry, address _deviceRegistry, ISnarkVerifier[8] memory _verifiers) {
        creatorRegistry = CreatorRegistry(_creatorRegistry);
        deviceRegistry = DeviceRegistry(_deviceRegistry);

        transformationVerifiers[Transformation.Blur] = _verifiers[0];
        transformationVerifiers[Transformation.Brightness] = _verifiers[1];
        transformationVerifiers[Transformation.Contrast] = _verifiers[2];
        transformationVerifiers[Transformation.Crop] = _verifiers[3];
        transformationVerifiers[Transformation.Grayscale] = _verifiers[4];
        transformationVerifiers[Transformation.Redact] = _verifiers[5];
        transformationVerifiers[Transformation.Resize] = _verifiers[6];
        transformationVerifiers[Transformation.Sharpness] = _verifiers[7];
    }

    /**
     * @notice Registers a new original asset captured by a verified device.
     * @param creator The address of the asset creator.
     * @param imageHash The uint256 hash of the original image.
     * @param captureTime Unix timestamp when the image was captured.
     * @param license The licensing details for the asset.
     * @param deviceId The address of the device that captured the image.
     * @param deviceSignature The device’s signature over (creator, imageHash, captureTime).
     */
    function registerNewAsset(
        address creator,
        uint256 imageHash,
        uint256 captureTime,
        License license,
        address deviceId,
        bytes calldata deviceSignature
    ) external {
        // 1. Ensure the creator is verified.
        require(creatorRegistry.verifyCreator(creator), "Creator not verified");

        // 2. Create a message hash for device signature verification and vaildate it.
        bytes32 messageHash = keccak256(abi.encodePacked(creator, imageHash, captureTime));
        require(
            deviceRegistry.verifyDeviceSignature(messageHash, deviceSignature, deviceId),
            "Invalid device signature"
        );

        // 3. Increment asset count and store the original asset.
        assetCount++;
        assets[assetCount] = Asset({
            creator: creator,
            imageHash: imageHash,
            captureTime: captureTime,
            license: license,
            timestamp: block.timestamp,
            sourceAssetId: 0,
            transformation: Transformation.NoTransformation
        });

        emit AssetRegistered(
            assetCount,
            creator,
            imageHash,
            captureTime,
            license,
            deviceId,
            0,
            Transformation.NoTransformation,
            block.timestamp
        );
    }

    function registerEditedAsset(
        address creator,
        uint256 editedImageHash,
        uint256 sourceAssetId,
        Transformation transformation,
//        uint256[25] calldata proof,
        License license
    ) external {
        // 1. Ensure the creator is verified.
        require(creatorRegistry.verifyCreator(creator), "Creator not verified");

        // 2. Ensure the source asset exists.
        require(sourceAssetId > 0 && sourceAssetId <= assetCount, "Source asset does not exist");

        // 3. Ensure the transformation is valid.
        require(transformation != Transformation.NoTransformation, "Invalid transformation");
        // TODO

        // 3. Increment asset count and store the asset.
        assetCount++;
        assets[assetCount] = Asset({
            creator: creator,
            imageHash: editedImageHash,
            captureTime: 0, // TODO
            license: license,
            timestamp: block.timestamp,
            sourceAssetId: sourceAssetId,
            transformation: transformation
        });

        emit AssetRegistered(
            assetCount,
            creator,
            editedImageHash,
            0, // TODO
            license,
            address(0), // TODO
            sourceAssetId,
            transformation,
            block.timestamp
        );
    }

    /**
     * @notice Retrieves details for a given asset by its ID.
     * @param assetId The asset's unique ID.
     * @return The asset's full details.
     */
    function getAsset(uint256 assetId) external view returns (Asset memory) {
        require(assetId > 0 && assetId <= assetCount, "Asset does not exist");
        return assets[assetId];
    }
}
