[profile.default]
src = "contracts"
libs = ["contract-deps"]

remappings = [
    "forge-std/=contract-deps/forge-std/src/",
    "openzeppelin-contracts/=contract-deps/openzeppelin-contracts/contracts/",
]

[rpc_endpoints]
anvil = "http://localhost:8545"

[doc]
out = "contract-docs"
